#
# Adapted from various sources, including:
# https://github.com/gabime/spdlog
#
language: cpp


compiler: clang


# # TODO: gcc 8.0
# addons: &gcc8
#   apt:
#     packages:
#       - g++-8
#     sources:
#       - ubuntu-toolchain-r-test

addons:
  apt:
    packages:
      - ninja
      - llvm
  homebrew:
    packages:
      - ninja
      - llvm
      - make


matrix:
  include:
    # # Test gcc-7.5: C++14, Build=Debug  MAKE=make GEN=Ninja
    # - env: GCC_VERSION=7 BUILD_TYPE=Debug CPP=14
    #   os: linux
    #   dist: bionic

    # # Test clang-7.0: C++14, Build=Debug MAKE=make GEN=Ninja
    # - env: CLANG_VERSION=7 BUILD_TYPE=Debug CPP=14
    #   os: linux
    #   dist: bionic

    # Test clang-12.2: C++14, Build=Debug
    - env: BUILD_TYPE=Debug CPP=14 MAKE=gmake GEN=Ninja #XXX CXX=clang++-12.2
      - PATH=/usr/local/opt/llvm/bin/:${PATH}
      os: osx
      osx_image: xcode12.2


before_script:
  - ${CXX} --version
  - ${MAKE} --version
  - cmake --version
  - ninja --version
  - pwd


script:
  - cd ${TRAVIS_BUILD_DIR}

  # - pwd
  # - mkdir -p build && pushd build
  # - |
  #   cmake .. -G ${GEN}\
  #     --warn-uninitialized \
  #     -DCMAKE_BUILD_TYPE=$BUILD_TYPE \

  # - pwd
  # - cmake --build . -- all
  # #NO! - ctest -j2 --output-on-failure
  # - popd

  - pwd
  - ${MAKE} build
  - ${MAKE} all
  - ${MAKE} check


notifications:
  email: false
