#
# Adapted from various sources, including:
# https://github.com/gabime/spdlog
#
language: cpp


# # TODO: gcc 8.0
# addons: &gcc8
#   apt:
#     packages:
#       - g++-8
#     sources:
#       - ubuntu-toolchain-r-test


matrix:
  include:
    # Test gcc-7.5: C++14, Build=Debug
    - env: GCC_VERSION=7 BUILD_TYPE=Debug CPP=14
      os: linux
      dist: bionic

    # Test clang-7.0: C++14, Build=Debug
    - env: CLANG_VERSION=7 BUILD_TYPE=Debug CPP=14
      os: linux
      dist: bionic

    # Test clang-9.1: C++14, Build=Debug
    - env: BUILD_TYPE=Debug CPP=14
      os: osx


before_script:
  - cmake --version
  - make --version
  - pwd


script:
  - cd ${TRAVIS_BUILD_DIR}
  - pwd
  - mkdir -p build && cd build
  - |
    cmake .. \
      --warn-uninitialized \
      -DCMAKE_BUILD_TYPE=$BUILD_TYPE \

  - pwd
  - cmake --build build -- all
  #NO! - cd build && ctest -j2 --output-on-failure

  - pwd
  - make all
  #XXX - make check


notifications:
  email: false
