#
# Adapted from various sources, including:
# https://github.com/gabime/spdlog
#
language: cpp


# # gcc 8.0
# addons: &gcc8
#   apt:
#     packages:
#       - g++-8
#     sources:
#       - ubuntu-toolchain-r-test
#
#
# # Clang 7.0
# addons: &clang70
#   apt:
#     packages:
#       - clang-7
#     sources:
#       - ubuntu-toolchain-r-test
#       - llvm-toolchain-trusty-7


matrix:
  include:
    # # Test gcc-8: C++17, Build=Debug
    # - env: GCC_VERSION=8 BUILD_TYPE=Debug CPP=17
    #   os: linux
    #   addons: *gcc8

    # Test clang-7.0: C++14, Build=Debug
    - env: CLANG_VERSION=7 BUILD_TYPE=Debug CPP=14
      os: linux
      dist: bionic

    # Test clang-9.1: C++14, Build=Debug
    - env: BUILD_TYPE=Debug CPP=14
      os: osx


before_script:
  #XXX - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  #XXX - if [ -n "$CLANG_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi
  #XXX - $CXX --version
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CXX="clang++" CC="clang"; fi
  - cmake --version
  - make --version


script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p build
  - cmake -B build -S ${PWD} --warn-uninitialized \
      -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
      -DCMAKE_CXX_STANDARD=${CPP} \

  - cmake --build build -- all
  #XXX - cd build && ctest -j2 --output-on-failure
  - make all
  - make check


notifications:
  email: false
