---
name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
  CXX: clang++
  CC: clang

jobs:
  # XXX
  # job1:
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - name: Add nina to Build Environment
  #     run: sudo apt-get install ninja-build llvm

  # XXX
  # job2:
  #   runs-on: macos-latest
  #   steps:
  #   - name: Add nina to Build Environment
  #     run: brew install ninja

  build:
    # XXX needs: [job1, job2]

    # The CMake configure and build commands are platform agnostic and
    # should work equally well on Windows or Mac.  You can convert this
    # to a matrix build if you need cross-platform coverage.
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false  # Keep running other jobs even if one fails
      matrix:
        # TODO: llvm_version: [10, 11, 12]
        os: [macos-latest, ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2

      - name: Configure Ubuntu Host
        if: startsWith(matrix.os, 'ubuntu')
        shell: bash
        run: |
          sudo apt-get update

          sudo apt-get install \
            llvm-10 clang-10 libclang-10-dev clang-tidy-10 ||
              echo IGNORED

          # TODO fmt is not available
          sudo apt-get install \
            cereal \
            doctest \
            ninja-build

      - name: Configure MacOS Host
        if: startsWith(matrix.os, 'macos')
        shell: bash
        run: |
          # coreutils is for gtimeout
          # make is for gmake
          brew install \
            coreutils \
            doctest \
            cereal \
            ninja \
            make \
            fmt \
            python

      # - name: Add nina to Build Environment
      #   shell: bash
      #   run: |
      #     test $OSTYPE != "darwin19" &&
      #     sudo apt-get install ninja-build || brew install ninja

      - name: Create Build Environment
        shell: bash
        # Some projects don't allow in-source building, so create a
        # separate build directory We'll use this as our working
        # directory for all subsequent commands
        run: |
          cmake -E make_directory ${{runner.workspace}}/build &&
          make library.a

      - name: Install builddriver
        shell: bash
        run: |
          pip3 install builddriver &&
          ln -s /Library/Frameworks/Python.framework/Versions/3.9/bin/builddriver .

      - name: Configure CMake
        # Use a bash shell so we can use the same syntax for environment
        # variable access regardless of the host operating system
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -G Ninja

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        # Execute the build.
        run: cmake --build . --config $BUILD_TYPE --target all

      - name: Test
        working-directory: ${{runner.workspace}}/build
        shell: bash
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html
        run: ctest -C $BUILD_TYPE || echo IGNORED

      - name: Clang Analyser Checks
        shell: bash
        run: make all check || echo IGNORED

      - name: Run clang-tidy
        run: |
          /home/runner/.local/bin/builddriver run-clang-tidy-10 ||
          builddriver /usr/local/opt/llvm/bin/run-clang-tidy ||
          which builddriver || echo IGNORED
